### ISSUE TITLE
you used github wikis

### ISSUE THREAD

**Issue by RooRay** [TnologyMC/TnologyMC#2]
nobody uses github wikis, use [gitbook ](https://www.gitbook.com/)or [wiki.js](https://js.wiki/) (haha not .py cry about it) instead

**Comment by Bloxs** [comment]
We used github wikis as they're easy to set up and look decent, we may consider using something such as [Docusaurus](https://docusaurus.io/) in the future if we ever need something github doesn't offer. I'm personally not a fan of gitbook and haven't tried wiki.js so we likely won't be using those.
